config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'goals#index'

  resources :goals, only: [ :index, :show, :new, :create ] do
    resources :tasks, only: [ :new, :create ]
  end

end

app/models/goal.rb
class Goal < ActiveRecord::Base
    validates :name, :presence => true
    validates :description, :presence => true

    has_many :tasks
end

app/models/task.rb
class Task < ActiveRecord::Base
  validates :name, :presence => true
  validates :description, :presence => true

  belongs_to :goal
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  def index
    if params[ :order_by ]
      order_by = params[ :order_by ]
      order = params[ :order ] == 'desc' ? 'desc' : 'asc'

      @goals = Goal.order( { order_by => order } )
    else
      @goals = Goal.all
    end
  end

  def show
    begin
      @goal = Goal.find( params[ :id ] )
    rescue
      @goal = nil
    end
  end

  def new
    @goal = Goal.new
  end

  def create
    @goal = Goal.new( goal_params( params ) )

    if @goal.save
        redirect_to @goal
    else
      render :new
    end
  end

  private
  def goal_params( params )
    return params.require( :goal ).permit( :name, :description )
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def new
    @goal = Goal.find( params[ :goal_id ] )
    @task = Task.new
  end

  def create
    @goal = Goal.find( params[ :goal_id ] )
    @task = Task.new( task_params( params ) )

    @goal.tasks << @task

    if @task.save
      redirect_to( goal_path( @goal ) )
    else
      render :new
    end
  end

  private
  def task_params( params )
    return params.require( :task ).permit( :name, :description )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/goals/index.html.erb
<section class="row">
  <div class="col-xs-8 col-xs-offset-2">
    <h1>Goals#index</h1>
    <% if @goals && !@goals.empty? %>
        <% @goals.each do | g | %>
          <a href="<%= goal_path( g ) %>">
            <article>
                <h2><%= g.name %></h2>
                <p><%= g.description %></p>
                <p>Total Tasks: <strong><%= g.tasks.length %></strong></p>
            </article>
          </a>
        <% end %>
    <% end %>
  </div>
</section>

app/views/goals/new.html.erb
<h1>Goals#new</h1>
<%= form_for @goal do | f |%>
  <ul>
    <li>
      <%= f.label :name %>
      <%= f.text_field :name %>
    </li>
    <li>
      <%= f.label :description %>
      <%= f.text_area :description %>
    </li>
    <li>
      <%= f.submit %>
    </li>
  </ul>
<% end %>

app/views/goals/show.html.erb
<h1>Goals#show</h1>
<% if @goal %>
    <h2><%= @goal.name %></h2>
    <p><%= @goal.description %></p>
    <% if !@goal.tasks.empty? %>
      <ul>
      <% @goal.tasks.each do | t | %>
        <li><%= t.name %></li>
      <% end %>
      </ul>
    <% else %>
      <h3>Whoops! This Goal does not have any tasks.</h3>
    <% end %>
    <a href="<%= new_goal_task_path( @goal ) %>">
      <button class="btn">Create New Task</button>
    </a>
<% else %>
    <h2>Whoops! Looks like this goal doesn't exist.</h2>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Goale</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<header>
  <!-- /// TODO[@jrmykolyn] - Only print markup if `notice`/`alert` are truth-y. -->
  <section class="preheader">
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  </section>
</header>
<main class="container">
  <%= yield %>
</main>

</body>
</html>

app/views/tasks/new.html.erb
<h1>Tasks#new</h1>
<%= form_for [ @goal, @task ] do | f | %>
  <ul>
    <li>
      <%= f.label :name %>
      <%= f.text_field :name %>
    </li>
    <li>
      <%= f.label :description %>
      <%= f.text_area :description %>
    </li>
    <li>
      <%= f.submit %>
    </li>
  </ul>
<% end %>